name: pyoncatqt-developer
channels:
  - conda-forge
  - mantid/label/nightly
  - oncat
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - mantidqt
  - pre-commit
  - pyoncat
  - python-build
  - pytest
  - pytest-cov
  - setuptools
  - versioningit
